version: '3.3'

services:
  go:
    build:
      context: .
      dockerfile: containers/go/Dockerfile
    tty: true
    volumes:
      - ./go:/app
    ports:
      - 8080:8080
      - 9090:9090
      - 6060:6060
    depends_on:
      - postgres
    env_file:
      - .env.dev
    # command: sh -c "go run cmd/rest/server.go"

  # postgres:
  #   image: postgres:15.2
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env.dev

  # postgres_test:
  #   image: postgres:15.2
  #   volumes:
  #     - postgres_data_test:/var/lib/postgresql/data
  #   ports:
  #     - 5430:5432
  #   env_file:
  #     - .env.dev

  # pgadmin4:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 8888:80
  #   volumes:
  #     - pgadmin4_data:/var/lib/pgadmin
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env.dev

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: containers/frontend/Dockerfile
  #   tty: true
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - 5173:5173
  #   command: sh -c "npm install && npm run dev"

# volumes:
#   postgres_data:
#   postgres_data_test:
#   pgadmin4_data:
